apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-profile-${BUILD_ENV}
  namespace: ${BUILD_ENV}
  labels:
    app: my-profile-${BUILD_ENV}
spec:
  replicas: 2
  minReadySeconds: 10
  selector:
    matchLabels:
      app: my-profile-${BUILD_ENV}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  template:
    metadata:
      labels:
        app: my-profile-${BUILD_ENV}
    spec:
      containers:
        - name: my-profile
          image: yadavsudhir405/my-profile:${BUILD_NUMBER}
          envFrom:
            - configMapRef:
                name: my-profil-configs-${BUILD_ENV}
          ports:
            - containerPort: 4000
