apiVersion: v1
kind: Service
metadata:
  name: my-profile-svc-${BUILD_ENV}
  labels:
    app: my-profile-${BUILD_ENV}
spec:
  type: NodePort
  ports:
    - port: ${PORT_NUMBER}
      targetPort: 4000
      protocol: TCP
  selector:
    app: my-profile-${BUILD_ENV}
