apiVersion: v1
kind: Service
metadata:
  name: my-profile-svc-${BUILD_ENV}
  labels:
    app: my-profile-${BUILD_ENV}
spec:
  ports:
    - targetPort: 4000
      port: 4000
      protocol: TCP
  selector:
    app: my-profile-${BUILD_ENV}
