apiVersion: v1
kind: Service
metadata:
  name: my-profile-svc-${BUILD_ENV}
  labels:
    app: my-profile-${BUILD_ENV}
spec:
  type: NodePort
  ports:
    - targetPort: 4000
      nodePort: ${PORT_NUMBER}
      port: 30019
      protocol: TCP
  selector:
    app: my-profile-${BUILD_ENV}
