export const typography = {
  fontFamily: 'Open Sans',
  fontWeightLight: 300,
  fontWeightRegular: 500,
  fontWeightMedium: 600,
  fontWeightBold: 700,
  fontWeights: {
    light: 300,
    normal: 500,
    lightBold: 600,
    bold: 700,
  },
  h1: {
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: '30px',
    lineHeight: '36px',
    letterSpacing: '-1.5px',
  },
  h2: {
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: '23px',
    lineHeight: '32px',
  },
  h3: {
    fontStyle: 'normal',
    fontWeight: 300,
    fontSize: '19px',
    lineHeight: '27px',
  },
  body: {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '14px',
    lineHeight: '20px',
  },
  small: {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '11px',
    lineHeight: '20px',
  },
  overline: {
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '11px',
    lineHeight: '20px',
    letterSpacing: '2px',
    textTransform: 'uppercase',
  },
  'mob-h1': {
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: '32px',
    lineHeight: '37px',
    letterSpacing: '-1.5px',
  },
  'mob-h2': {
    fontStyle: 'normal',
    fontWeight: '300',
    fontSize: '30px',
    lineHeight: '35px',
    letterSpacing: '-0.5px',
  },
  'mob-h3': {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '27px',
    lineHeight: '32px',
  },
  'mob-body1': {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '22px',
    letterSpacing: '0.3px',
  },
  'mob-body2': {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '14px',
    lineHeight: '20px',
    letterSpacing: '0.25px',
  },
  'mob-subtitle1': {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '16px',
    lineHeight: '24px',
    letterSpacing: '0.15px',
  },
  'mob-subtitle2': {
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '14px',
    lineHeight: '24px',
    letterSpacing: '0.1px',
  },
  'mob-caption': {
    fontStyle: 'normal',
    fontWeight: 'normal',
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '0.4px',
  },
  'mob-small': {
    fontStyle: 'normal',
    fontWeight: 600,
    fontSize: '12px',
    lineHeight: '16px',
    letterSpacing: '1.6px',
    textTransform: 'uppercase',
  },
};
